services:
  - type: web
    name: writing-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
    domains:
      - writing-assistant.innatec3.com
