services:
  - type: web
    name: writing-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --timeout=120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: CLAUDE_MODEL
        value: claude-3-sonnet
      - key: FLASK_ENV
        value: production
    domains:
      - writing-assistant.innatec3.com
